apiVersion: projectcalico.org/v3
kind: NetworkPolicy
metadata:
  name: app-hipstershop.productcatalogservice
  namespace: hipstershop
spec:
  tier: app-hipstershop
  order: 1400
  selector: app == "productcatalogservice"
  ingress:
    - action: Allow
      protocol: TCP
      source:
        selector: >-
          app == "checkoutservice-XXXX"||app == "frontend-XXXX"||app ==
          "recommendationservice-XXXX"
      destination:
        ports:
          - "3550"
  types:
    - Ingress
